
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  - platform: rpi_gpio #requires rpi_gpio installation via HACS
    switches:
      - port: 4
        name: "relay1"
        invert_logic: true
      - port: 17
        name: "relay2"
        invert_logic: true
      - port: 22
        name: "relay3"
        invert_logic: true
      - port: 5
        name: "relay4"
        invert_logic: true
      - port: 6
        name: "relay5"
        invert_logic: true
      - port: 13
        name: "relay6"
        invert_logic: true
      - port: 19
        name: "relay7"
        invert_logic: true
      - port: 26
        name: "relay8"
        invert_logic: true

# Input for micro switch as a sensor for a completely closed door
binary_sensor:
  - platform: rpi_gpio
    sensors:
      - port: 11
        name: "Door completely closed"
        unique_id: "door_completely_closed"
        pull_mode: "DOWN"
        invert_logic: true
        bouncetime: 80
